name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
      
    - name: Set up .NET
      uses: actions/setup-dotnet@v1.0.0
      with:
        dotnet-version: '4.7.2'
    - name: Run build
      run: msbuild CamLog.sln
