name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Restore
      run: dotnet restore CamLog.sln
    - name: Run build
      run: dotnet build -p:Version=1.0.0.${{ github.run_number }} CamLog.sln 
    - uses: actions/upload-artifact@v2
      with:
        name: CamLog
        path: UI/bin/Debug/net472/* # or path/to/artifact